name: nasaPrj

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
        mongodb-version:
          - 4.4.6
    env:
      CI: true
      MONGODB_URL: mongodb://localhost:27017/nasaPrj
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm test
